// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxYNC3INq5EJ95-ciI3nAANf6qncudY3s',
    appId: '1:33040509420:web:9d1eae5f23d2c607bab8c9',
    messagingSenderId: '33040509420',
    projectId: 'duobr-4ac3f',
    authDomain: 'duobr-4ac3f.firebaseapp.com',
    storageBucket: 'duobr-4ac3f.firebasestorage.app',
    measurementId: 'G-LMRC5NS3RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxBv7nYyyZJE_b_FKupWxMzokha77ZWeE',
    appId: '1:33040509420:android:e09f4ad73b5903afbab8c9',
    messagingSenderId: '33040509420',
    projectId: 'duobr-4ac3f',
    storageBucket: 'duobr-4ac3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEvtwJH1lrBqtNqx3HZPTJN-4o4a0kJzQ',
    appId: '1:33040509420:ios:20649fc432f11988bab8c9',
    messagingSenderId: '33040509420',
    projectId: 'duobr-4ac3f',
    storageBucket: 'duobr-4ac3f.firebasestorage.app',
    iosClientId: '33040509420-ud83v4vpsjle8gd4tkb32408oli10flk.apps.googleusercontent.com',
    iosBundleId: 'com.example.duobrProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEvtwJH1lrBqtNqx3HZPTJN-4o4a0kJzQ',
    appId: '1:33040509420:ios:20649fc432f11988bab8c9',
    messagingSenderId: '33040509420',
    projectId: 'duobr-4ac3f',
    storageBucket: 'duobr-4ac3f.firebasestorage.app',
    iosClientId: '33040509420-ud83v4vpsjle8gd4tkb32408oli10flk.apps.googleusercontent.com',
    iosBundleId: 'com.example.duobrProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxYNC3INq5EJ95-ciI3nAANf6qncudY3s',
    appId: '1:33040509420:web:2c1a5432280ca2cabab8c9',
    messagingSenderId: '33040509420',
    projectId: 'duobr-4ac3f',
    authDomain: 'duobr-4ac3f.firebaseapp.com',
    storageBucket: 'duobr-4ac3f.firebasestorage.app',
    measurementId: 'G-RENREZFGEM',
  );

}